#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
:PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/tldr/chenla-d9d/README.org
  :Created:   2017-06-22T10:46@Prek Leap (11.642600N-104.919210W)
  :ID:        c22cb9e9-09c4-4c68-b82f-a357832ac46d
  :VER:       551375245.987783557
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:YVI6-7120
  :Class:     deploy
  :Type:      readme
  :Status:    stub 
  :Licence:   MIT/CC BY-SA 4.0
:END:

* Chenla d9d Services

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]]
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-readme-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-stub-CC79A7.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

Introduction and overview of Chenla Institutes d9d (distrubuted) services.

D9D Services started as a OpenStack Cluster which was first deployed
in 2015 at Repozit Technologies' office in Phnom Penh.  Persistent
problems with flooding prompted moving the cluster to Prek Leap
National College of Agriculture in 2016.

We are in the process of phasing out OpenStack and virtual machines to
Docker containerized processes, managed by Kubernetes as part of
Red Hat's OpenShift container platform.  We will also be deploying a
Ceph storage cluster.

The new system is expected to be brought online third quarter 2017.

--- 

*NOTE*: The primary repo is @ [[http://git.chenla.org/d9d/chenla-d9d ]] Please
submit pull requests and issues there.  A read-only mirror is
maintained @ [[https://github.com/chenla/chenla-d9d ]]
